# Generated by Django 4.0.6 on 2022-10-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id_aspirante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aspirante', models.CharField(max_length=45)),
                ('correo_aspirante', models.CharField(max_length=45)),
                ('presentacion_aspirante', models.CharField(max_length=1000)),
                ('cedulaciudadania', models.PositiveIntegerField(default=0)),
                ('certificaciones', models.CharField(max_length=200)),
                ('experiencia', models.CharField(max_length=1000)),
                ('fecha_nacimiento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=45)),
                ('correo_empresa', models.CharField(max_length=45)),
                ('presentacion_empresa', models.CharField(max_length=1000)),
                ('nit', models.CharField(max_length=45)),
                ('sectorEconomico', models.CharField(choices=[('Primario', 'Primario'), ('Secundario', 'Secundario'), ('Terciario', 'Terciario'), ('Cuaternario', 'Cuaternario')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('contrasena_usuario', models.CharField(max_length=45)),
                ('tipo_usuario', models.CharField(choices=[('Empresa', 'Empresa'), ('Aspirante', 'Aspirante')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_Oferta', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=45)),
                ('perfil_buscado', models.CharField(max_length=200)),
                ('salario', models.PositiveIntegerField(default=0)),
                ('Empresa_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_match', models.DateTimeField(auto_now_add=True)),
                ('tipo_match', models.CharField(choices=[('Perfecto', 'Perfecto'), ('Muy bueno', 'Muy bueno'), ('Bueno', 'Bueno'), ('Medio', 'Medio')], max_length=45)),
                ('porcentaje', models.PositiveIntegerField(default=0)),
                ('Aspirante_id_aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.aspirante')),
                ('Empresa_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.empresa')),
                ('Oferta_id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.oferta')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
        migrations.CreateModel(
            name='documentacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politicas', models.CharField(max_length=1000)),
                ('tyc', models.CharField(max_length=1000)),
                ('Empresa_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='documentacionAspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdv', models.CharField(max_length=1000)),
                ('recomendaciones', models.CharField(max_length=1000)),
                ('Aspirante_id_aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.aspirante')),
            ],
        ),
        migrations.AddField(
            model_name='aspirante',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
    ]
