# Generated by Django 4.0.6 on 2022-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='Nombre_empresa',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
