# Generated by Django 4.0.6 on 2022-11-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_match_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id_empresa',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
