# Generated by Django 4.0.6 on 2022-10-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_oferta_empresa_id_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='Empresa_nombre_empresa',
        ),
        migrations.AddField(
            model_name='oferta',
            name='Nombre_empresa',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
