# Generated by Django 4.0.6 on 2022-11-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_empresa_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id_empresa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sectorEconomico',
            field=models.CharField(max_length=45),
        ),
    ]
